server:
  port: ${PORT:8080}
spring:
  messages:
    basename: i18n/messages
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 5_242_880
      max-request-size: 5_242_880
word-search:
  name: @project.name@
  version: @project.version@
  description: @project.description@
  temporary-directory-path: ${TEMPORARY_DIRECTORY_PATH:${java.io.tmpdir}}
  ocr:
    maximum-duration: 40_000
    data-path: ${TESSDATA_PREFIX}
    language: FRA