server:
  port: ${PORT:8080}
spring:
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 5_242_880
      max-request-size: 5_242_880
word-search:
  cors:
    allowed-headers: "*"
    allowed-methods: GET,POST,HEAD,OPTIONS,PUT,DELETE
    allowed-origins: "http://localhost:4200"
  errors:
    internal-server-error:
      title: Erreur interne du serveur
      detail: No details available.
    constraint-violation:
      title: Erreur de validation
    max-upload-size-exceeded:
      title: Taille maximale d'upload atteinte
      detail: La requête a été rejetée car sa taille (%s) excède le maximum configuré (${spring.servlet.multipart.max-request-size}).
    optical-character-recognition-error:
      title: Le fichier ne peut être converti
      detail: No details available.
    unsupported-format:
      title: Format de fichier non-supporté