spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 5_242_880
      max-request-size: 5_242_880
word-search:
  cors:
    allowed-headers: "*"
    allowed-methods: GET,POST,HEAD,OPTIONS,PUT,DELETE
    allowed-origins: "http://localhost:4200"